paths = ["src"]
output = "output"

[publish]
"ex.github" = {version = "3.0.0"}
"ex.reproto" = {version = "1.0.0"}

[packages]
"ex.reproto.blog" = {version = "^1"}
"ex.reproto.toystore" = {version = "^1"}
"ex.github.gists" = {version = "^3"}
"ex.github.pulls" = {version = "^3"}
"ex.github.service" = {version = "^3"}
